/**
 * Puzzler 2018
 * Control your bot. Collect. Store. Win.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Puzzler2018) {
      root.Puzzler2018 = {};
    }
    root.Puzzler2018.Action = factory(root.Puzzler2018.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class Action.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "stay"
     * @const
     */
    "stay": "stay",
    /**
     * value: "up"
     * @const
     */
    "up": "up",
    /**
     * value: "down"
     * @const
     */
    "down": "down",
    /**
     * value: "left"
     * @const
     */
    "left": "left",
    /**
     * value: "right"
     * @const
     */
    "right": "right"  };

  /**
   * Returns a <code>Action</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/Action} The enum <code>Action</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


