/**
 * Puzzler 2018
 * Control your bot. Collect. Store. Win.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Puzzler2018) {
      root.Puzzler2018 = {};
    }
    root.Puzzler2018.BoardPiece = factory(root.Puzzler2018.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class BoardPiece.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "bot"
     * @const
     */
    "bot": "bot",
    /**
     * value: "enemy"
     * @const
     */
    "enemy": "enemy",
    /**
     * value: "collectible"
     * @const
     */
    "collectible": "collectible",
    /**
     * value: "bot_base"
     * @const
     */
    "bot_base": "bot_base",
    /**
     * value: "enemy_base"
     * @const
     */
    "enemy_base": "enemy_base"  };

  /**
   * Returns a <code>BoardPiece</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/BoardPiece} The enum <code>BoardPiece</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


