/**
 * Puzzler 2018
 * Control your bot. Collect. Store. Win.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BoardPiece', 'model/EntityPosition'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BoardPiece'), require('./EntityPosition'));
  } else {
    // Browser globals (root is window)
    if (!root.Puzzler2018) {
      root.Puzzler2018 = {};
    }
    root.Puzzler2018.Entity = factory(root.Puzzler2018.ApiClient, root.Puzzler2018.BoardPiece, root.Puzzler2018.EntityPosition);
  }
}(this, function(ApiClient, BoardPiece, EntityPosition) {
  'use strict';




  /**
   * The Entity model module.
   * @module model/Entity
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Entity</code>.
   * @alias module:model/Entity
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Entity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Entity} obj Optional instance to populate.
   * @return {module:model/Entity} The populated <code>Entity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('boardPiece')) {
        obj['boardPiece'] = BoardPiece.constructFromObject(data['boardPiece']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], Object);
      }
      if (data.hasOwnProperty('ownerId')) {
        obj['ownerId'] = ApiClient.convertToType(data['ownerId'], 'Number');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = EntityPosition.constructFromObject(data['position']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BoardPiece} boardPiece
   */
  exports.prototype['boardPiece'] = undefined;
  /**
   * @member {Object} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} ownerId
   */
  exports.prototype['ownerId'] = undefined;
  /**
   * @member {module:model/EntityPosition} position
   */
  exports.prototype['position'] = undefined;



  return exports;
}));


