/**
 * Puzzler 2018
 * Control your bot. Collect. Store. Win.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityAction', 'model/TickBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntityAction'), require('./TickBase'));
  } else {
    // Browser globals (root is window)
    if (!root.Puzzler2018) {
      root.Puzzler2018 = {};
    }
    root.Puzzler2018.TickRequest = factory(root.Puzzler2018.ApiClient, root.Puzzler2018.EntityAction, root.Puzzler2018.TickBase);
  }
}(this, function(ApiClient, EntityAction, TickBase) {
  'use strict';




  /**
   * The TickRequest model module.
   * @module model/TickRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TickRequest</code>.
   * @alias module:model/TickRequest
   * @class
   * @extends module:model/TickBase
   */
  var exports = function() {
    var _this = this;
    TickBase.call(_this);
  };

  /**
   * Constructs a <code>TickRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TickRequest} obj Optional instance to populate.
   * @return {module:model/TickRequest} The populated <code>TickRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      TickBase.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(TickBase.prototype);
  exports.prototype.constructor = exports;




  return exports;
}));


